#Fruit shope list
cat("Welcome to my fruit shop🍇","\n")
cat("Here is your order Menu:","\n")
cat("apple       -₹99","\n")
cat("mango       -₹89","\n")
cat("grapes      -₹79","\n")
cat("watermelon  -₹69","\n")
cat("Lichhi      -₹59","\n")
cat("banana      -₹49","\n")
input<-as.numeric(readline("please enter 1 to 6:"))
chose<-switch(input,"apple","mango","graps","watermelon","Lichhi","banana")
qun<-as.numeric(readline("Enter quantity:"))
cat("your order summary!","\n","\n")
cat(chose,"\n")
cat("quantity:",qun,"\n")
vac<-c(99,89,79,69,59,49)
total<-cat("total₹",vac[input]*qun)
